import 'dart:math';

/// placeholder list of AI generated scrambles
final List<String> scrambleList = [
  "R U R' U R U2 R'",
  "F R U' R' U' R U R' F'",
  "L U2 L' U2 L F' L' U' L U L F L2",
  "B U B' U' B' R B2 U' B' U' B U B' R'",
  "R' U' F' U F R",
  "U R U' L' U R' U' L",
  "F2 L D2 L' F2 L D2 L'",
  "R U2 R2 U' R2 U' R2 U2 R",
  "F U R U' R2 F' R U R U' R'",
  "U R2 F B' R B R2 U R U2 R'",
  "L' U' L U' L' U2 L",
  "R' U2 R2 U R2 U R2 U2 R'",
  "F R' F' R2 U R U' R' U R U2 R'",
  "R U R' U R U2 R' U",
  "F' L F R' F' L' F R",
  "B2 R2 U' B2 U' B2 R2 U R2",
  "U' L U' L' U' L U2 L'",
  "D R' D' R2 U R U' R' U R U2 R'",
  "L U2 L2 U' L2 U' L2 U2 L",
  "R2 U' F B' R B R2 U R U2 R'",
  "U2 B R2 U2 B R2 U2 B R2 U2",
  "L' U2 L2 U L2 U L2 U2 L'",
  "F' U2 F2 U' F2 U' F2 U2 F",
  "R U' R' U' R U R D R' U' R D' R'",
  "R2 B2 U2 F' U' B2 R2 U' F R2",
  "F U2 R2 F' L' U' L F R2 U2 F'",
  "U R U' R U' R' U R2 D R' U' R D' R2",
  "L2 U F' B L B' L2 U' F L2",
  "R' F' L F R U2 R' F' L' F R",
  "F' L F L' U' L' U L",
  "F2 D R2 U' R2 U R2 D' F2",
  "R2 F B' R B R2 F' R B R'",
  "U' F R2 D R' U2 R D' R2 F'",
  "F2 D' L2 D2 F2 D' L2 D F2",
  "L' U' L U' L' U2 L",
  "R' U' R' D' R' U R' D R2",
  "F' R' F R2 U R U' R' U R U2 R'",
  "F R' F' R U2 R U2 R'",
  "R2 U R' B' R U' R2 U R B U' R'",
  "L' B' R' D2 R B L D2",
  "R U2 R' U2 R U R' U R U' R'",
  "F R' F R2 U' R U R' U' R U2 R'",
  "B L' B' L U' L U2 L'",
  "R2 U' R2 U R2 U R2 U2 R2",
  "F' L F L' U L' U L",
  "U R2 D R' U2 R D' R2 U' R U2 R'",
  "B R' B' R2 U R U' R' U R U2 R'",
  "F' L' F L U2 L U2 L'",
  "R' F R F' U2 F' U2 F",
];

/// Returns a random scramble from the list
String getRandomScramble() {
  final random = Random();
  return scrambleList[random.nextInt(scrambleList.length)];
}
